version: '3'

tasks:
  test:
    cmd: deno test -A --unstable --parallel --ignore=lib/libsql/ {{ .DIR }}

  cache:
    cmd: deno cache deps.ts 

  dev:
    deps:
    - cache
    cmd: deno run -A --unstable cmd/typhoon-awe/dev.ts
    silent: true

  apply:
    cmds: 
      - infisical run --env=prod -- atlas schema apply --env=iam
    # ENV with default as `dev`