version: '3'

tasks:
  test:
    cmd: deno test -A --unstable --parallel --ignore=lib/libsql/ {{.CLI_ARGS}}

  cache:
    cmd: deno cache deps.ts 

  dev:
    deps:
    - cache
    cmd: infisical run --path=typhoon-awe --env=dev -- deno run -A --unstable cmd/typhoon-awe/dev.ts
    silent: true

  env:
    cmds:
      - infisical secrets --path=typhoon-awe --env=dev {{.CLI_ARGS}}

  # Move this to deploy in gh action maybe?
  turso:
    cmds: 
      - infisical run --path=typhoon-awe --env=prod -- atlas schema apply --env=iam