version: '3'

dotenv:
  - .env

tasks:
  test:
    deps:
      - cache
    cmd: deno test -A --unstable --parallel --ignore=lib/libsql/ {{.CLI_ARGS}}

  cache:
    cmd: deno cache deps.ts 

  dev:
    deps:
      - cache
    cmds: 
      - atlas schema apply --env=local --auto-approve
      - infisical run --path=/typhoon-awe --env=dev -- deno run -A --unstable cmd/typhoon-awe/dev.ts {{.CLI_ARGS}}
    silent: true

  env:
    cmds:
      - infisical secrets --path=/typhoon-awe {{.CLI_ARGS}}

  # Move this to deploy in gh action maybe?
  turso:
    cmds: 
      - infisical run --path=/typhoon-awe --env=prod -- atlas schema apply --env=iam