version: '3'

tasks:
  test:
    cmd: deno test -A --unstable --parallel --ignore=lib/libsql/ {{ .DIR }}

  cache:
    cmd: deno cache deps.ts 

  dev:
    deps:
    - cache
    cmd: infisical run --path=typhoon-awe --env=dev -- deno run -A --unstable cmd/typhoon-awe/dev.ts
    silent: true

  env:
    cmds:
      - infisical secrets --env=dev --path=typhoon-awe {{.CLI_ARGS}}

  turso:
    cmds: 
      - infisical run --path=typhoon-awe --env=prod -- atlas schema apply --env=iam
    # ENV with default as `dev`